* NumPy(Numeric Python)is one of the most important foundational packages fror numerical computing in python
* open source python library
* The numpy library contains multidimensional array data structures  such as the homogeneous ,N- dimensional ndarray and a large library of fns that operate efficiently on these data structures.

### Why do we use python numpy?
* less memory
* fast 
* easy to understand
* vecotrization(way faster than loops in list)

### Why not use Python in-built data structure 
* Python's built-in data structures like lists and tuples are not optimized for numerical computations.
* NumPy provides a more efficient way to store and manipulate large datasets, especially for mathematical operations.
* NumPy arrays are more memory-efficient.
* NumPy provides a wide range of mathematical functions and operations that are specifically designed for numerical computing, making it easier to perform complex calculations on large datasets.

### Import Numpy as np

In [ ]:
import numpy as nmy

Myarray = nmy.array([1, 2, 3, 4, 5])
print(Myarray, type(Myarray))

In [ ]:
import numpy as nmy
arr = nmy.array([1, 2, 3])
print(arr)

In [3]:
import numpy as nmy

# ARRAYS ::

# 0D Array 
arr_0d = nmy.array(42)
print("ndim:", arr_0d.ndim) 
print("shape:", arr_0d.shape)
print("size:", arr_0d.size)
print("itemsize:", arr_0d.itemsize)
print("dtype:", arr_0d.dtype)
print("type:", type(arr_0d))
print(arr_0d)

# 1D Array 
arr_1d = nmy.array(range(1, 4))
print("ndim:", arr_1d.ndim) 
print("shape:", arr_1d.shape)
print("size:", arr_1d.size)
print("itemsize:", arr_1d.itemsize)
print("dtype:", arr_1d.dtype)
print("type:", type(arr_1d))
print(arr_1d)


# 2D Array 
arr_2d = nmy.array([[1, 2, 3], [4, 5, 6]])
print("ndim:", arr_2d.ndim) 
print("shape:", arr_2d.shape) 
print("size:", arr_2d.size)
print("itemsize:", arr_2d.itemsize)
print("dtype:", arr_2d.dtype)
print("type:", type(arr_2d))
print(arr_2d)

# 3D Array 
arr_3d = nmy.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("ndim:", arr_3d.ndim) 
print("shape:", arr_3d.shape) 
print("size:", arr_3d.size)
print("itemsize:", arr_3d.itemsize)
print("dtype:", arr_3d.dtype)
print("type:", type(arr_3d))
print(arr_3d)


ndim: 0
shape: ()
size: 1
itemsize: 8
dtype: int64
type: <class 'numpy.ndarray'>
42
ndim: 1
shape: (3,)
size: 3
itemsize: 8
dtype: int64
type: <class 'numpy.ndarray'>
[1 2 3]
ndim: 2
shape: (2, 3)
size: 6
itemsize: 8
dtype: int64
type: <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
ndim: 3
shape: (2, 2, 2)
size: 8
itemsize: 8
dtype: int64
type: <class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np

# zeros() - Creates an array filled with 0s
zeros_arr = np.zeros((2, 3))
print("zeros:\n", zeros_arr)

# ones() - Creates an array filled with 1s
ones_arr = np.ones((3, 2))
print("\nones:\n", ones_arr)

# full() - Creates an array filled with a specific constant value
full_arr = np.full((2, 2), 7)
print("\nfull:\n", full_arr)

# eye() - Creates an identity matrix (1s on the diagonal, 0s elsewhere)
eye_arr = np.eye(3)
print("\neye:\n", eye_arr)

# arange() - Creates an array with regularly spaced values (start, stop, step)
arange_arr = np.arange(0, 10, 2)
print("\narange:\n", arange_arr)

# linspace() - Creates an array with a specified number of evenly spaced values over a range
linspace_arr = np.linspace(0, 1, 5)
print("\nlinspace:\n", linspace_arr)

# random.rand() - Creates an array filled with random floats between 0 and 1
random_arr = np.random.rand(2, 2)
print("\nrandom:\n", random_arr)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

full:
 [[7 7]
 [7 7]]

eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

arange:
 [0 2 4 6 8]

linspace:
 [0.   0.25 0.5  0.75 1.  ]

random:
 [[0.33790807 0.37273201]
 [0.88181464 0.13527163]]


In [ ]:
import numpy as np
import sys
List1 = [12, 3, 4, 5, 6, 7, 8, 9]
# Prints Python list object memory overhead (~112 bytes)
print(sys.getsizeof(List1))  
arr = np.array(List1)
# Manually calculates total bytes of array data (8 elements * 8 bytes = 64 bytes)
print(arr.size * arr.itemsize)
# Directly returns total bytes consumed by the NumPy array data buffer (64 bytes)
print(arr.nbytes)  

120
64
64


In [3]:
import numpy as np
import time

# Define ranges with matching lengths for a fair comparison
l1 = range(1, 100000)
l2 = range(1, 100000)

# Convert to NumPy arrays (fixing the initial typos)
A1 = np.array(l1)
A2 = np.array(l2)

# Time Python List Comprehension
start = time.time()
result_list = [x + y for x, y in zip(l1, l2)]
print(f"List comprehension time: {time.time() - start:.5f} seconds")

# Time NumPy Vectorized Addition
start = time.time()
result_np = A1 + A2
print(f"NumPy vectorization time: {time.time() - start:.5f} seconds")

List comprehension time: 0.03204 seconds
NumPy vectorization time: 0.00103 seconds


## Vectorization
* Vectorization means performing operations on entire arrays at once intesd of using Pythin loops
* It is fast as numpy usues optimized C code intenrnally 
* works on same shape array.

In [ ]:
import numpy as np
import time

# NumPy Vectorization Test
start = time.time()
arr = np.arange(100000)
arr2 = arr * 2
end = time.time()
print(f"NumPy time: {end - start:.6f} seconds")

# Python List Comprehension Test
start = time.time()
lst = [x for x in range(100000)]
lst2 = [x * 2 for x in lst]
end = time.time()
print(f"List time: {end - start:.6f} seconds")

NumPy time: 0.001790 seconds
List time: 0.016417 seconds


In [5]:
import numpy as np

# Create two NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 1. Element-wise addition
addition = a + b  # array([5, 7, 9])

# 2. Element-wise multiplication
multiplication = a * b  # array([4, 10, 18])

# 3. Dot product (matrix/vector product)
dot_product = np.dot(a, b)  # 32 (1*4 + 2*5 + 3*6 = 4 + 10 + 18)

print("Addition:", addition)
print("Multiplication:", multiplication)
print("Dot Product:", dot_product)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product: 32


## Broadcasting
* Opertions between diffrent shape arrrays.
* NumPy automatically expands the smaller array ( without copying ) so shapes become compatible

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = 5  # second array of the same shape

print(a + b)

[6 7 8]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = 5  # second array of the same shape

print(a**b)

[  1  32 243]


In [12]:
import numpy as np

arr = np.array([1, 2, 3])
vec = np.array([10, 20, 30])  # Corrected 1D array

print(arr + vec)
# Output: [11 22 33]

[11 22 33]


### How to use Python NumPy To genrate Random
* .numpy.random.rand() --  genrate random float from 0 to 1 of a given size
* np.random.randint(low, high, size) -- generates an array of random integers from the low (inclusive) up to, but not including, the high (exclusive) limit.
* np.random.choice(a, size, replace, p)-- generates a random sample from a given 1-D array (or an integer range), allowing you to pick elements with or without replacement and assign custom probabilities to each item.

In [13]:
import numpy as np
x=np.random.rand(10)
print(x)

[0.37409056 0.13329225 0.14649478 0.33478757 0.68999098 0.11660275
 0.26545246 0.97220564 0.82343799 0.73829627]


In [1]:
import numpy as np
x=np.random.rand(10)
print(x)
# it is goign to creat  1D array 

[0.95600434 0.54932587 0.38395189 0.53387339 0.12103201 0.76816772
 0.64067127 0.98633058 0.58097682 0.10030839]


In [2]:
import numpy as np
x=np.random.rand(3,5)
print(x)

[[0.19220104 0.31846695 0.14590827 0.83767467 0.50021311]
 [0.86463329 0.29316492 0.95121233 0.08080698 0.22188611]
 [0.69148804 0.7209651  0.56637068 0.36942871 0.96386886]]


In [ ]:
import numpy as np
x= np.random.randint(5,10,size=10)
print(x)

[7 9 9 8 5 8 5 6 7 7]


In [4]:
import numpy as np
x= np.random.randint(5,10,size=(5,2))
print(x)

[[7 9]
 [5 5]
 [6 9]
 [7 7]
 [8 8]]


In [5]:
import numpy as np
numbers = np.array([10, 20, 30, 40, 50])
print(np.random.choice(numbers, size=3)) 
print(np.random.choice(10, size=4, replace=False)) 

[30 40 50]
[2 1 0 9]


### Accessing elements from an array
* indexing in NumPy is quite similar to Python's standard indexing

In [6]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # First element: 10
print(arr[2])   # Third element: 30
print(arr[-1])  # Last element: 50

10
30
50


### Indexing and Slicing 
* Contenets of ndarray object can be accessed and modified by indexing or slicing.

In [9]:
import numpy as np

# Creating a 2-D array with 3 arrays (rows)
x = np.array([[10, 20, 30, 40],[50, 60, 70, 80],[90, 100, 110, 120]])
# Slice the first 2 arrays (rows)
print(x[:2]) 
# Slice specific rows and columns using [row_slice, col_slice]
# Get rows 0 to 2, and columns from index 1 up to 3
print(x[0:2, 1:3]) 
# Get all rows, but only a specific column (e.g., column index 2)
print(x[:, 2]) 

[[10 20 30 40]
 [50 60 70 80]]
[[20 30]
 [60 70]]
[ 30  70 110]


In [10]:
import numpy as np
x = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

# Slice rows 0 to 2 (excludes index 2) and columns 1 to 3 (excludes index 3)
sub_matrix = x[0:2, 1:3]

print(sub_matrix)

[[20 30]
 [50 60]]


#### VIEW

In [ ]:
import numpy as np

# Create a 1D NumPy array with 4 elements
arr = np.array([1, 2, 3, 4])

# Slice the array from index 1 to 2 (elements 2 and 3).
# NumPy slicing creates a "view" of the original array, NOT a copy.
s = arr[1:3]

# Modify the first element of the view 's' to 100.
# Because 's' shares memory with 'arr', this also changes arr[1] to 100.
s[0] = 100

# Print the original array. 
print(arr)

# Print the slice/view 's'.
print(s)

# Check the '.base' attribute of the view.
# This returns the original array that 's' is borrowing data from.
print(s.base)

[  1 100   3   4]
[100   3]
[  1 100   3   4]


##### FANCY INDEXING

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
f=arr[[1,2]]
f[0]=500
print(arr)
print(f)
print(f.base)


[1 2 3 4]
[500   3]
None


In [12]:
import numpy as np

x = np.random.randint(100, size=(10, 6))
print("Original Array:\n", x)
print("\nSlice (rows 2-4, cols 2-5):")
print(x[2:5, 2:6])
print("\nColumns 1, 3, and 5:")
print(x[:, [1, 3, 5]])
print("\nRows 1-4 mixed with columns 1, 3, and 5:")
print(x[1:5, [1, 3, 5]])

Original Array:
 [[ 0 19 80 29 87  0]
 [ 1 27 89 31 99 74]
 [67 99 92  1 79 29]
 [37 73 58 74 53  7]
 [72 15 29 15 95 25]
 [ 7 96 14 66 33 48]
 [69  9 45  2 21 62]
 [54 82 45 33 51  2]
 [73 65 43 74 48 71]
 [47 71 77 11 20 74]]

Slice (rows 2-4, cols 2-5):
[[92  1 79 29]
 [58 74 53  7]
 [29 15 95 25]]

Columns 1, 3, and 5:
[[19 29  0]
 [27 31 74]
 [99  1 29]
 [73 74  7]
 [15 15 25]
 [96 66 48]
 [ 9  2 62]
 [82 33  2]
 [65 74 71]
 [71 11 74]]

Rows 1-4 mixed with columns 1, 3, and 5:
[[27 31 74]
 [99  1 29]
 [73 74  7]
 [15 15 25]]


##### Boolean Array Indexing / Filter
* this type of advanced indexing is used when the resultant object is meant to be the reult of Boolean opertions , such as compariosn operators.
* the samw wya we can apply to the filter function.

In [ ]:
import numpy as np
x = np.array([12, 23, 45, 67, 89])
even_numbers = x[x % 2 == 0]
print(even_numbers)

In [2]:
import numpy as np

x = np.array([[12, 23, 45, 67, 89],[10, 20, 30, 40, 50],[1, 3, 5, 7, 9]])
even_numbers = x[x % 2 == 0]
print(even_numbers)

[12 10 20 30 40 50]


### Advanced NumPy Operations
* Reshaping Arrays
* Transposing Arrays
* Rotating Arrays
* Joining Arrays
* Splitting Arrays
* Data Types for ndarrays
* Arithmetic with NumPy Array

In [16]:
import numpy as np
n=np.arange(1,13)
print(n)
x=n.reshape((3,4))
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
import numpy as np
n=np.arange(1,13)
print(n)
x=n.reshape((3,4))
print(x)
print(x.reshape(-1))
print(n.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# RESHAPING OF ARRAY

import numpy as np
n=np.arange(1,13)
print(n)

x=n.reshape((6,2))
print(x)


# again change back to 1D=> FLAT IN

#FLAT IN -> used in ML
print(x.reshape(-1))

In [ ]:
x=np.random.randint(10,size=(2,3))
print(x)

print(x.reshape(-1))

In [ ]:
# Joining Array
# 1D

x=np.array([1,2,3])
y=np.array([4,5,6])

print(np.concatenate((x,y),axis=0))
# print(np.concatenate((x,y),axis=1))

In [ ]:
# 2D

x=np.array([[1,2,3],[4,5,6]])
y=np.array([[4,4,4],[2,2,2]])

print(np.concatenate((x,y),axis=0))#increase in row(vertical stacking)
print(np.concatenate((x,y),axis=1))#increase in column(horizontal stacking)


# different dimensions  give error

In [ ]:
#Vertical Stack
print(np.vstack((x,y))) #it is similar to print(np.concatenate((x,y),axis=0))
print(np.hstack((x,y))) #it is similar to print(np.concatenate((x,y),axis=1))

#### Arithmetic with NumPy Arrays
* arrays are i  important because they are enable you to express batch operations on data without writing any for loops
* Nu

In [5]:
import numpy as np

# Define two 2x3 arrays
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[2, 2, 2], [3, 3, 3]])

# Addition
add_result = x + y
print("Addition (x + y):\n", add_result)

# Subtraction
sub_result = x - y
print("\nSubtraction (x - y):\n", sub_result)

# Multiplication
mul_result = x * y
print("\nMultiplication (x * y):\n", mul_result)

# Division
div_result = x / y
print("\nDivision (x / y):\n", div_result)

# Power
power_result = x ** y
print("\nPower (x ** y):\n", power_result)

# Floor Division
floor_div_result = x // y
print("\nFloor Division (x // y):\n", floor_div_result)

# Modulus
mod_result = x % y
print("\nModulus (x % y):\n", mod_result)

# Negative
neg_result = np.negative(x)
print("\nNegative (np.negative(x)):\n", neg_result)

Addition (x + y):
 [[3 4 5]
 [7 8 9]]

Subtraction (x - y):
 [[-1  0  1]
 [ 1  2  3]]

Multiplication (x * y):
 [[ 2  4  6]
 [12 15 18]]

Division (x / y):
 [[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]

Power (x ** y):
 [[  1   4   9]
 [ 64 125 216]]

Floor Division (x // y):
 [[0 1 1]
 [1 1 2]]

Modulus (x % y):
 [[1 0 1]
 [1 2 0]]

Negative (np.negative(x)):
 [[-1 -2 -3]
 [-4 -5 -6]]


In [6]:
import numpy as np

# Define two 2x3 arrays
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[2, 2, 2], [3, 3, 3]])

# Addition
add_result = np.add(x, y)
print("Addition (np.add):\n", add_result)

# Subtraction
sub_result = np.subtract(x, y)
print("\nSubtraction (np.subtract):\n", sub_result)

# Multiplication
mul_result = np.multiply(x, y)
print("\nMultiplication (np.multiply):\n", mul_result)

# Division
div_result = np.divide(x, y)
print("\nDivision (np.divide):\n", div_result)

# Power
power_result = np.power(x, y)
print("\nPower (np.power):\n", power_result)

# Floor Division
floor_div_result = np.floor_divide(x, y)
print("\nFloor Division (np.floor_divide):\n", floor_div_result)

# Modulus
mod_result = np.mod(x, y)
print("\nModulus (np.mod):\n", mod_result)

# Negative
neg_result = np.negative(x)
print("\nNegative (np.negative):\n", neg_result)

Addition (np.add):
 [[3 4 5]
 [7 8 9]]

Subtraction (np.subtract):
 [[-1  0  1]
 [ 1  2  3]]

Multiplication (np.multiply):
 [[ 2  4  6]
 [12 15 18]]

Division (np.divide):
 [[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]

Power (np.power):
 [[  1   4   9]
 [ 64 125 216]]

Floor Division (np.floor_divide):
 [[0 1 1]
 [1 1 2]]

Modulus (np.mod):
 [[1 0 1]
 [1 2 0]]

Negative (np.negative):
 [[-1 -2 -3]
 [-4 -5 -6]]


In [ ]:
import numpy as np
x=np.array([-2,-3,-1,0,1,2])
np.absolute(x)

array([2, 3, 1, 0, 1, 2])

In [15]:
import numpy as np

x = [1, 2, 3]

print("Exp2:", np.exp2(x))
print("Log2:", np.log2(x))
print("Log10:", np.log10(x))

Exp2: [2. 4. 8.]
Log2: [0.        1.        1.5849625]
Log10: [0.         0.30103    0.47712125]


### Advanced Ufunc Features
#### Specifying output
* For large calculations , it is sometimes useful to be able to specify the array where the result of the calculation will be stored.
#### Aggregations ( Reduce method)
* If you like to reduce an array with a particular operation, we can use the reduce method of any unfunc
* A reduce repeatedly applies a given operation to the elements of an array ony a single result remains 

In [16]:
import numpy as np
x=np.arange(2,20,2)
print(x)
z=np.empty(9)
print(z)
print(np.multiply(x, 10 , out=z))


[ 2  4  6  8 10 12 14 16 18]
[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.86921686e-306
 1.89146896e-307 7.56571288e-307 3.11525958e-307 1.24610723e-306
 0.00000000e+000]
[ 20.  40.  60.  80. 100. 120. 140. 160. 180.]


In [17]:
import numpy as np
x=np.arange(1,11)
print(x)
np.add.reduce(x)
np.add.accumulate(x)

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
import numpy as np

# Define a 2x3 array
x = np.array([[1, 2, 3], [4, 5, 6]])

# Sum (adds all elements together)
sum_result = np.sum(x)
print("Sum (np.sum):\n", sum_result)

# Product (multiplies all elements together)
prod_result = np.prod(x)
print("\nProduct (np.prod):\n", prod_result)

# Cumulative Sum (computes the running total)
cumsum_result = np.cumsum(x)
print("\nCumulative Sum (np.cumsum):\n", cumsum_result)

# Cumulative Product (computes the running multiplication)
cumprod_result = np.cumprod(x)
print("\nCumulative Product (np.cumprod):\n", cumprod_result)

In [2]:
import numpy as np

x = np.arange(1, 101).reshape(10, 10)
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [3]:
import numpy as np

# Recreating your 10x10 matrix
x = np.arange(1, 101).reshape(10, 10)

print("--- Basic Statistics ---")
print("Sum:", np.sum(x))              # Total sum of all elements
print("Mean (Average):", np.mean(x))  # Average value
print("Median:", np.median(x))        # Middle value
print("Standard Deviation:", np.std(x)) # Measure of spread
print("Variance:", np.var(x))         # Variance

print("\n--- Extrema & Indices ---")
print("Minimum:", np.min(x))          # Lowest value
print("Maximum:", np.max(x))          # Highest value
print("Argmin (Index of min):", np.argmin(x)) # Flat index of minimum
print("Argmax (Index of max):", np.argmax(x)) # Flat index of maximum

print("\n--- Products & Cumulative Operations ---")
small_x = np.arange(1, 6)
print("Product:", np.prod(small_x))       # Product of elements (1*2*3*4*5)
print("Cumulative Sum:", np.cumsum(small_x)) # [1, 3, 6, 10, 15]
print("Cumulative Product:", np.cumprod(small_x)) # [1, 2, 6, 24, 120]

print("\n--- Logical Aggregations ---")
bool_x = np.array([True, True, False])
print("All (are all True?):", np.all(bool_x))
print("Any (is any True?):", np.any(bool_x))

print("\n--- Axis-Specific Aggregations (Using your 10x10 matrix) ---")
print("Sum of each column (axis=0):", x.sum(axis=0))
print("Sum of each row (axis=1):", x.sum(axis=1))

--- Basic Statistics ---
Sum: 5050
Mean (Average): 50.5
Median: 50.5
Standard Deviation: 28.86607004772212
Variance: 833.25

--- Extrema & Indices ---
Minimum: 1
Maximum: 100
Argmin (Index of min): 0
Argmax (Index of max): 99

--- Products & Cumulative Operations ---
Product: 120
Cumulative Sum: [ 1  3  6 10 15]
Cumulative Product: [  1   2   6  24 120]

--- Logical Aggregations ---
All (are all True?): False
Any (is any True?): True

--- Axis-Specific Aggregations (Using your 10x10 matrix) ---
Sum of each column (axis=0): [460 470 480 490 500 510 520 530 540 550]
Sum of each row (axis=1): [ 55 155 255 355 455 555 655 755 855 955]


In [8]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, np.nan, 6, 7, 8, 9])

print("--- Standard Aggregations with NaN ---")
print("Sum:", np.sum(x))              # Result: nan
print("Mean:", np.mean(x))            # Result: nan
print("Median:", np.median(x))        # Result: nan
print("Standard Deviation:", np.std(x)) # Result: nan
print("Variance:", np.var(x))         # Result: nan
print("Minimum:", np.min(x))          # Result: nan
print("Maximum:", np.max(x))          # Result: nan

print("\n--- Index and Cumulative Functions ---")
print("Argmin (Index of min):", np.argmin(x)) # Result: 5 (Points to NaN)
print("Argmax (Index of max):", np.argmax(x)) # Result: 5 (Points to NaN)
print("Cumulative Sum:", np.cumsum(x))       # Result: [1., 3., 6., 10., 15., nan, nan, nan, nan, nan]
print("Cumulative Product:", np.cumprod(x)) # Result: [1., 2., 6., 24., 120., nan, nan, nan, nan, nan]

--- Standard Aggregations with NaN ---
Sum: nan
Mean: nan
Median: nan
Standard Deviation: nan
Variance: nan
Minimum: nan
Maximum: nan

--- Index and Cumulative Functions ---
Argmin (Index of min): 5
Argmax (Index of max): 5
Cumulative Sum: [ 1.  3.  6. 10. 15. nan nan nan nan nan]
Cumulative Product: [  1.   2.   6.  24. 120.  nan  nan  nan  nan  nan]


In [9]:
import numpy as np

# Generate the random array of 10 integers between 1 and 9
x = np.random.randint(1, 10, size=10)
print("Array x:", x)

# Find the indices where the element equals 3
indices = np.where(x == 3)
print("Indices where 3 is located:", indices)

# Extract the actual positions (since np.where returns a tuple)
print("Flat indices:", indices[0])

Array x: [2 1 8 1 3 1 2 3 2 8]
Indices where 3 is located: (array([4, 7]),)
Flat indices: [4 7]


In [ ]:
import numpy as np

# Generate the random array
x = np.random.randint(1, 10, size=10)
print("Array x:", x)

# 1. Find the indices where x > 4
indices = np.where(x > 4)
print("Indices where x > 4:", indices[0])

# 2. Extract the actual values where x > 4 (Boolean Indexing)
values = x[x > 4]
print("Values where x > 4:", values)

In [10]:
import numpy as np

# Generate the random array
x = np.random.randint(1, 10, size=10)
print("Original Array x:", x)

# 1. np.sort() - Returns a sorted copy of the array
sorted_x = np.sort(x)
print("Sorted Array (np.sort):", sorted_x)

# 2. np.argsort() - Returns the indices that would sort the array
sorted_indices = np.argsort(x)
print("Sorted Indices (np.argsort):", sorted_indices)

# Verification: You can use the argsort indices to reorder the original array
print("Reordering original array using argsort indices:", x[sorted_indices])

Original Array x: [7 7 5 5 4 6 9 2 9 9]
Sorted Array (np.sort): [2 4 5 5 6 7 7 9 9 9]
Sorted Indices (np.argsort): [7 4 3 2 5 1 0 6 8 9]
Reordering original array using argsort indices: [2 4 5 5 6 7 7 9 9 9]


In [12]:
import numpy as np

# 1. Initialize the random array
print("=== 1. INITIAL ARRAY ===")
x = np.random.randint(1, 10, size=10)
print("Original Array x:", x)

# 2. Searching with np.where() and Boolean Indexing
print("\n=== 2. SEARCHING & FILTERING ===")

# Find where elements equal 3
indices_3 = np.where(x == 3)
print("Indices where x == 3:", indices_3[0])

# Find where elements are greater than 4
indices_gt_4 = np.where(x > 4)
print("Indices where x > 4:", indices_gt_4[0])
print("Values where x > 4 (Boolean Masking):", x[x > 4])

# Multiple conditions: x > 3 AND x < 8
complex_indices = np.where((x > 3) & (x < 8))
print("Indices where 3 < x < 8:", complex_indices[0])
print("Values matching condition:", x[complex_indices])

# 3. Sorting with np.sort() and np.argsort()
print("\n=== 3. SORTING ===")

# Sort the actual values
sorted_x = np.sort(x)
print("Sorted Array (np.sort):    ", sorted_x)

# Get the sorting indices
sorted_indices = np.argsort(x)
print("Sorted Indices (np.argsort):", sorted_indices)
print("Reordered via indices:     ", x[sorted_indices])

# 4. Partial Sorting with np.partition()
print("\n=== 4. PARTIAL SORTING ===")
# Quickly place the 3 smallest elements on the left side
partitioned = np.partition(x, 3)
print("Partitioned Array:         ", partitioned)

=== 1. INITIAL ARRAY ===
Original Array x: [7 7 5 2 7 6 7 4 5 2]

=== 2. SEARCHING & FILTERING ===
Indices where x == 3: []
Indices where x > 4: [0 1 2 4 5 6 8]
Values where x > 4 (Boolean Masking): [7 7 5 7 6 7 5]
Indices where 3 < x < 8: [0 1 2 4 5 6 7 8]
Values matching condition: [7 7 5 7 6 7 4 5]

=== 3. SORTING ===
Sorted Array (np.sort):     [2 2 4 5 5 6 7 7 7 7]
Sorted Indices (np.argsort): [3 9 7 2 8 5 0 1 6 4]
Reordered via indices:      [2 2 4 5 5 6 7 7 7 7]

=== 4. PARTIAL SORTING ===
Partitioned Array:          [2 2 4 5 5 6 7 7 7 7]


In [13]:
import numpy as np

# Generate a random 1D array of 10 integers between 1 and 20
x = np.random.randint(1, 21, size=10)
print("Original Array x:", x)

# 1. Basic Filtering (e.g., elements greater than 10)
mask = x > 10
filtered_basic = x[mask]
print("\n--- 1. Basic Filtering (x > 10) ---")
print("Boolean Mask:", mask)
print("Filtered Values:", filtered_basic)

# 2. Multiple Conditions (AND: x > 5 AND x < 15)
# Note: You must use parentheses around each condition and the bitwise '&' operator
filtered_and = x[(x > 5) & (x < 15)]
print("\n--- 2. Multiple Conditions (5 < x < 15) ---")
print("Filtered Values:", filtered_and)

# 3. Multiple Conditions (OR: x < 5 OR x > 15)
# Use the bitwise '|' operator for OR
filtered_or = x[(x < 5) | (x > 15)]
print("\n--- 3. Multiple Conditions (x < 5 OR x > 15) ---")
print("Filtered Values:", filtered_or)

# 4. Using np.extract()
# Extract only even numbers
even_numbers = np.extract(x % 2 == 0, x)
print("\n--- 4. Using np.extract (Even Numbers) ---")
print("Even Values:", even_numbers)

# 5. Filtering and Modifying with np.where()
# Keep values > 10, but replace any value <= 10 with 0
modified_x = np.where(x > 10, x, 0)
print("\n--- 5. Filtering & Modifying (np.where) ---")
print("Modified Array (<=10 turned to 0):", modified_x)

Original Array x: [13  3 11 12  3 12  9  8 17 12]

--- 1. Basic Filtering (x > 10) ---
Boolean Mask: [ True False  True  True False  True False False  True  True]
Filtered Values: [13 11 12 12 17 12]

--- 2. Multiple Conditions (5 < x < 15) ---
Filtered Values: [13 11 12 12  9  8 12]

--- 3. Multiple Conditions (x < 5 OR x > 15) ---
Filtered Values: [ 3  3 17]

--- 4. Using np.extract (Even Numbers) ---
Even Values: [12 12  8 12]

--- 5. Filtering & Modifying (np.where) ---
Modified Array (<=10 turned to 0): [13  0 11 12  0 12  0  0 17 12]
